- name: package
  package: name="{{ item }}" state="present"
  become: true
  with_items:
    - deluged
    - deluge-console
    - deluge-web
- name: service config
  template: src="templates/{{ item }}.service.j2" dest="/etc/systemd/system/{{ item }}.service" owner="root" group="root" mode="644"
  become: true
  notify: [reload deluge]
  with_items:
    - deluged
    - deluge-web
- name: deluged config
  template: src="templates/deluged.conf.j2" dest="/var/lib/deluged/config/core.conf" owner="debian-deluged" group="debian-deluged" mode="644"
  become: true
  notify: [reload deluge]
- name: service
  systemd: service="{{ item }}" enabled="true" state="started"
  become: true
  with_items:
    - deluged
    - deluge-web
