---
- name: sshd_config
  template: src="templates/sshd_config.j2" dest="/etc/ssh/sshd_config" owner="root" group="root" mode="644"
  become: true
  notify: [restart ssh]
- name: motd
  template: src="templates/motd.j2" dest="/etc/motd" owner="root" group="root" mode="644"
  become: true
- name: ipv6
  template: src="templates/disable-ipv6.conf.j2" dest="/etc/sysctl.d/70-disable-ipv6.conf" owner="root" group="root" mode="644"
  become: true
  notify: [reload sysctl]
- name: apt
  template: src="templates/sources.list.j2" dest="/etc/apt/sources.list" owner="root" group="root" mode="644"
  become: true
- name: samba
  package: name="samba-client" state="present"
  become: true
- name: fstab
  template: src="templates/fstab.j2" dest="/etc/fstab" owner="root" group="root" mode="644"
  become: true
- name: bluetooth package
  package: name="bluez" state="absent"
  become: true
- name: bluetooth service
  service: name="bluetooth" state="stopped"
  become: true
- name: tools
  package: name="{{ item }}" state="present"
  become: true
  with_items:
    - curl
    - dnsutils
    - htop
    - nmap
    - screen
- name: bashrc
  template: src="templates/bashrc.sh.j2" dest="~/.bashrc" mode="644"
